apiVersion: batch/v1
kind: Job
#apiVersion: batch/v1beta1
#kind: CronJob
metadata:
  name: noise
spec:
#  schedule: "@daily"
#  concurrencyPolicy: Forbid
#  jobTemplate:
#    spec:
  template:
    metadata:
      name: noise
    spec:
      containers:
      - name: pipelines
        image: orihoch/sk8s-pipelines
        command:
        - bash
        - "-c"
        - |
          rm -f /pipelines/data/done &&\
          dpp run ./noise &&\
          touch /pipelines/data/done
        volumeMounts:
        - name: data
          mountPath: /pipelines/data
#        envFrom:
#        - secretRef:
#            name: name-of-secret-containing-env-vars
      - name: ops
        image: orihoch/sk8sops:pipelines-google-storage-sync
        resources:
          requests:
            cpu: "0.01"
            memory: "100Mi"
        env:
        - name: K8S_ENVIRONMENT
          value: staging
        - name: GS_BUCKET_NAME
          value: bucket_name
        - name: OUTPUT_PATH_PREFIX
          value: additional_path_prefix
        volumeMounts:
        - name: data
          mountPath: /pipelines/data
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
      volumes:
      # this is the k8s ops secret, see https://github.com/OriHoch/sk8s-ops/blob/master/README.md#secrets
      - name: k8s-ops
        secret:
          secretName: ops
      # empty dir is stored on host and shared between all container in pod, we use it to sync data between the pods
      - name: data
        emptyDir: {}
      restartPolicy: Never
